const translations = {
    en: {
        "title": "Azka Fashion | Designer Indian Suits & Ethnic Wear Online",
        "nav.home": "HOME",
        "nav.shop": "SHOP",
        "nav.about": "ABOUT US",
        "nav.contact": "CONTACT US",
        "nav.menu": "☰",
        "nav.collection": "COLLECTION",
        "nav.login": "Login/Register",
        "nav.cart": "Cart",
        // UPDATED: Reflects Manufacturer/Retailer focus
        "banner.description": "Discover the Latest Designer Indian Suits and<br>Exclusive Ethnic Wear Collections Online.<br>Style, Quality, and Tradition, delivered globally.",
        "btn.about": "About us",
        "btn.arrivals": "New Arrivals",
        "btn.newarrivals": "New Arrivals",
        "btn.collection": "Collection",
        "product.lepremier": "LE PREMIER VOL-II",
        "product.summerglory": "SUMMER GLORY",
        "product.blisslawn": "BLISS LAWN 2024",
        "product.urbanechiffon": "URBANE CHIFFON DUP",
        "product.designersuit": "Designer Suit",
        "product.urbanedigitallawn": "URBANE DIGITAL LAWN",
        "product.urbanedigitallawnvol": "URBANE DIGITAL LAWN VOL",
        "product.price1": "₹8,500.00",
        "product.price2": "₹5,950.00",
        "product.price3": "₹4,400.00",
        "product.price4": "₹3,280.00",
        "product.price5": "₹2,920.00",
        "product.price6": "₹3,950.00",
        "footer.info": "Information",
        "footer.contact": "Contact & Address", // Consolidated with Address
        "footer.email": "Email: contact@example.com",
        "footer.phone": "Phone: +91 8447943029",
        "footer.developer": "Developer",
        "footer.developedby": "Developed by <span class=\"dev-name\">@nasir hussain</span>",
        "footer.copyright": "© 2025 All rights reserved",
        "footer.follow": "Follow Us",
        "modal.login": "Login",
        "modal.email": "Your email*",
        "modal.password": "Password*",
        "modal.forgot": "Forgot your password?",
        "modal.loginbtn": "Login",
        "modal.createaccount": "Create Account",
        "lang.en": "English",
        "lang.ja": "Japanese",
        "collection.title": "OUR COLLECTION",
        "filter": "FILTER",
        "filter.title": "Filter",
        "filter.category": "Category",
        "filter.availability": "Availability",
        "filter.instock": "In stock",
        "filter.outstock": "Out of stock",
        "filter.price": "Price",
        "sort.by": "Sort by:",
        "sort.featured": "Featured",
        "sort.bestselling": "Best selling",
        "sort.az": "Alphabetically, A-Z",
        "sort.za": "Alphabetically, Z-A",
        "sort.lowhigh": "Price, low to high",
        "sort.highlow": "Price, high to low",
        "sort.oldnew": "Date, old to new",
        "sort.newold": "Date, new to old",
        "footer.information": "Information",
        "footer.collection": "Collection",
        "footer.about": "About",
        "footer.contactus": "Contact",
        "product.ombre2025": "OMBRE 2025",
        "product.urbane1": "URBANE DIGITAL LAWN PRINTS",
        "product.urbane2": "URBANE DIGITAL LAWN VOL II",
        "addtocart": "Add to Cart",
        "buynow": "Buy Now",
        "pagination.prev": "&larr;",
        "pagination.next": "&rarr;",
        "contact.title": "Contact Our Team", // SEO improvement
        "sidebar.close": "Close",
        "contact.dropaline": "DROP US A LINE",
        "contact.or": "or",
        "contact.messageinsta": "message us on Instagram",
        "contact.name": "Your Name",
        "contact.email": "Your Email",
        "contact.number": "Your Number",
        "contact.story": "Your Inquiry / Wholesale Request", // Keyword rich
        "contact.submit": "Submit",
        "contact.offer": "OUR MANUFACTURING ADVANTAGES", // Reflecting business type
        "contact.qualitytitle": "Quality Assured",
        "contact.quality": "Our products are made under strict quality control. As a manufacturer, we guarantee rigorous testing for all fabrics and finished goods.",
        "contact.bespoketitle": "Ready-to-Wear & Unstitched", // Reflecting business type
        "contact.bespoke": "We specialize in both fully tailored Ready-to-Wear and high-quality Unstitched Designer Suits, providing flexibility for retailers and customers.",
        "contact.servicetitle": "Worldwide Shipping & Support",
        "contact.service": "Our team ensures seamless order processing and support. We handle shipping worldwide to deliver the latest trends directly to you.",
        "footer.menu": "MENU",
        "footer.privacy": "Privacy Policy",
        "footer.cookie": "Cookie Policy",
        "footer.designby": "Website Design by",
        "footer.nasir": "@nasir"
    },
    ja: {
        "title": "アズカファッション | デザイナーインドスーツ＆民族衣装オンライン",
        "nav.home": "ホーム",
        "nav.shop": "ショップ",
        "nav.about": "私たちについて",
        "nav.contact": "お問い合わせ",
        "nav.menu": "☰",
        "nav.collection": "コレクション",
        "nav.login": "ログイン/登録",
        "nav.cart": "カート",
        // UPDATED: Reflects Manufacturer/Retailer focus
        "banner.description": "最新の**デザイナーインドスーツ**と<br>**限定エスニックウェア**コレクションをオンラインで発見。<br>スタイル、品質、伝統を世界中にお届けします。",
        "btn.about": "私たちについて",
        "btn.arrivals": "新着商品",
        "btn.newarrivals": "新着商品",
        "btn.collection": "コレクション",
        "product.lepremier": "ル・プルミエ VOL-II",
        "product.summerglory": "サマーグローリー",
        "product.blisslawn": "ブリスローン 2024",
        "product.urbanechiffon": "アーバンシフォンデュプ",
        "product.designersuit": "デザイナースーツ",
        "product.urbanedigitallawn": "アーバンデジタルローン",
        "product.urbanedigitallawnvol": "アーバンデジタルローン VOL",
        "product.price1": "₹8,500.00",
        "product.price2": "₹5,950.00",
        "product.price3": "₹4,400.00",
        "product.price4": "₹3,280.00",
        "product.price5": "₹2,920.00",
        "product.price6": "₹3,950.00",
        "footer.info": "情報",
        "footer.contact": "連絡先と住所", // Consolidated with Address
        "footer.email": "メール: contact@example.com",
        "footer.phone": "電話: +91 8447943029",
        "footer.developer": "開発者",
        "footer.developedby": "<span class=\"dev-name\">@nasir hussain</span> によって開発されました",
        "footer.copyright": "© 2025 全著作権所有",
        "footer.follow": "フォローする",
        "modal.login": "ログイン",
        "modal.email": "メールアドレス*",
        "modal.password": "パスワード*",
        "modal.forgot": "パスワードをお忘れですか？",
        "modal.loginbtn": "ログイン",
        "modal.createaccount": "アカウント作成",
        "lang.en": "英語",
        "lang.ja": "日本語",
        "collection.title": "コレクション",
        "filter": "フィルター",
        "filter.title": "フィルター",
        "filter.category": "カテゴリー",
        "filter.availability": "在庫状況",
        "filter.instock": "在庫あり",
        "filter.outstock": "在庫なし",
        "filter.price": "価格",
        "sort.by": "並び替え:",
        "sort.featured": "おすすめ",
        "sort.bestselling": "ベストセラー",
        "sort.az": "アルファベット順, A-Z",
        "sort.za": "アルファベット順, Z-A",
        "sort.lowhigh": "価格が安い順",
        "sort.highlow": "価格が高い順",
        "sort.oldnew": "日付が古い順",
        "sort.newold": "日付が新しい順",
        "footer.information": "情報",
        "footer.collection": "コレクション",
        "footer.about": "私たちについて",
        "footer.contactus": "連絡先",
        "product.ombre2025": "オンブル 2025",
        "product.urbane1": "アーバンデジタルローンプリント",
        "product.urbane2": "アーバンデジタルローン VOL II",
        "addtocart": "カートに追加",
        "buynow": "今すぐ購入",
        "pagination.prev": "&larr;",
        "pagination.next": "&rarr;",
        "contact.title": "お問い合わせチーム",
        "sidebar.close": "×",
        "contact.dropaline": "ご連絡ください",
        "contact.or": "または",
        "contact.messageinsta": "Instagramでメッセージを送る",
        "contact.name": "お名前",
        "contact.email": "メールアドレス",
        "contact.number": "電話番号",
        "contact.story": "お問い合わせ内容 / 卸売に関するご要望",
        "contact.submit": "送信",
        "contact.offer": "製造上の利点",
        "contact.qualitytitle": "品質保証",
        "contact.quality": "当社の製品は厳格な品質管理の下で製造されています。メーカーとして、すべての生地と完成品に対して徹底したテストを保証します。",
        "contact.bespoketitle": "既製服と未縫製",
        "contact.bespoke": "既製服と高品質の未縫製デザイナーズスーツの両方に特化しており、小売業者とお客様に柔軟性を提供します。",
        "contact.servicetitle": "世界配送とサポート",
        "contact.service": "当社のチームは、シームレスな注文処理とサポートを保証します。最新のトレンドを直接お届けするため、世界中に配送いたします。",
        "footer.menu": "メニュー",
        "footer.privacy": "プライバシーポリシー",
        "footer.cookie": "クッキーポリシー",
        "footer.designby": "ウェブサイトデザイン：",
        "footer.nasir": "@nasir"
    }
};