const translations = {
    en: {
        "title": "Azka Fashion",
        "nav.home": "HOME",
        "nav.shop": "SHOP",
        "nav.about": "ABOUT US",
        "nav.contact": "CONTACT US",
        "nav.menu": "☰",
        "nav.collection": "Collection",
        "nav.login": "Login/Register",
        "nav.cart": "Cart",
        "banner.description": "Azka Fashion is a premium fabric design studio<br>crafting bespoke textiles and timeless styles<br>for modern retailers around the world.",
        "btn.about": "About us",
        "btn.arrivals": "New Arrivals",
        "btn.newarrivals": "New Arrivals",
        "btn.collection": "Collection",
        "product.lepremier": "LE PREMIER VOL-II",
        "product.summerglory": "SUMMER GLORY",
        "product.blisslawn": "BLISS LAWN 2024",
        "product.urbanechiffon": "URBANE CHIFFON DUP",
        "product.designersuit": "Designer Suit",
        "product.urbanedigitallawn": "URBANE DIGITAL LAWN",
        "product.urbanedigitallawnvol": "URBANE DIGITAL LAWN VOL",
        "product.price1": "₹8,500.00",
        "product.price2": "₹5,950.00",
        "product.price3": "₹4,400.00",
        "product.price4": "₹3,280.00",
        "product.price5": "₹2,920.00",
        "product.price6": "₹3,950.00",
        "footer.info": "Information",
        "footer.contact": "Contact",
        "footer.email": "Email: contact@example.com",
        "footer.phone": "+91 8447943029",
        "footer.developer": "Developer",
        "footer.developedby": "Developed by <span class=\"dev-name\">@nasir hussain</span>",
        "footer.copyright": "© 2025 All rights reserved",
        "footer.follow": "Follow Us",
        "modal.login": "Login",
        "modal.email": "Your email*",
        "modal.password": "Password*",
        "modal.forgot": "Forgot your password?",
        "modal.loginbtn": "Login",
        "modal.createaccount": "Create Account",
        "lang.en": "English",
        "lang.ja": "Japanese",
        "collection.title": "OUR COLLECTION",
        "filter": "FILTER",
        "filter.title": "Filter",
        "filter.category": "Category",
        "filter.availability": "Availability",
        "filter.instock": "In stock",
        "filter.outstock": "Out of stock",
        "filter.price": "Price",
        "sort.by": "Sort by:",
        "sort.featured": "Featured",
        "sort.bestselling": "Best selling",
        "sort.az": "Alphabetically, A-Z",
        "sort.za": "Alphabetically, Z-A",
        "sort.lowhigh": "Price, low to high",
        "sort.highlow": "Price, high to low",
        "sort.oldnew": "Date, old to new",
        "sort.newold": "Date, new to old",
        "footer.information": "Information",
        "footer.collection": "Collection",
        "footer.about": "About",
        "footer.contactus": "Contact",
        "product.ombre2025": "OMBRE 2025",
        "product.urbane1": "URBANE DIGITAL LAWN PRINTS",
        "product.urbane2": "URBANE DIGITAL LAWN VOL II",
        "addtocart": "Add to Cart",
        "buynow": "Buy Now",
        "pagination.prev": "&larr;",
        "pagination.next": "&rarr;",
        "contact.title": "Contact Us",
        "sidebar.close": "Close",
        "contact.dropaline": "DROP US A LINE",
        "contact.or": "or",
        "contact.messageinsta": "message us on Instagram",
        "contact.name": "Your Name",
        "contact.email": "Your Email",
        "contact.number": "Your Number",
        "contact.story": "Tell your story",
        "contact.submit": "Submit",
        "contact.offer": "What we offer",
        "contact.qualitytitle": "Quality Assured",
        "contact.quality": "Our customers are safe in the knowledge that our fabrics are subject to a strict quality control procedure and rigorous testing process.",
        "contact.bespoketitle": "Bespoke Solutions",
        "contact.bespoke": "Select your fabric from our extensive library, or if you’re looking for something more unique, we’ll work with you to create an original piece from scratch.",
        "contact.servicetitle": "Unrivalled Customer Service",
        "contact.service": "Our team work hard, so you don’t have to. Customer service has always been our top priority, and our designers and sales team are on hand to help every step of the way.",
        "footer.menu": "MENU",
        "footer.privacy": "Privacy Policy",
        "footer.cookie": "Cookie Policy",
        "footer.designby": "Website Design by",
        "footer.nasir": "@nasir"
    },
    ja: {
        "title": "アズカファッション",
        "nav.home": "ホーム",
        "nav.shop": "ショップ",
        "nav.about": "私たちについて",
        "nav.contact": "お問い合わせ",
        "nav.menu": "☰",
        "nav.collection": "コレクション",
        "nav.login": "ログイン/登録",
        "nav.cart": "カート",
        "banner.description": "Azka Fashionは、世界中の現代の小売業者向けに<br>特注のテキスタイルと時代を超えたスタイルを<br>制作するプレミアムファブリックデザインスタジオです。",
        "btn.about": "私たちについて",
        "btn.arrivals": "新着商品",
        "btn.newarrivals": "新着商品",
        "btn.collection": "コレクション",
        "product.lepremier": "ル・プルミエ VOL-II",
        "product.summerglory": "サマーグローリー",
        "product.blisslawn": "ブリスローン 2024",
        "product.urbanechiffon": "アーバンシフォンデュプ",
        "product.designersuit": "デザイナースーツ",
        "product.urbanedigitallawn": "アーバンデジタルローン",
        "product.urbanedigitallawnvol": "アーバンデジタルローン VOL",
        "product.price1": "₹8,500.00",
        "product.price2": "₹5,950.00",
        "product.price3": "₹4,400.00",
        "product.price4": "₹3,280.00",
        "product.price5": "₹2,920.00",
        "product.price6": "₹3,950.00",
        "footer.info": "情報",
        "footer.contact": "お問い合わせ",
        "footer.email": "メール: contact@example.com",
        "footer.phone": "+91 8447943029",
        "footer.developer": "開発者",
        "footer.developedby": "<span class=\"dev-name\">@nasir hussain</span> によって開発されました",
        "footer.copyright": "© 2025 全著作権所有",
        "footer.follow": "フォローする",
        "modal.login": "ログイン",
        "modal.email": "メールアドレス*",
        "modal.password": "パスワード*",
        "modal.forgot": "パスワードをお忘れですか？",
        "modal.loginbtn": "ログイン",
        "modal.createaccount": "アカウント作成",
        "lang.en": "英語",
        "lang.ja": "日本語",
        "collection.title": "コレクション",
        "filter": "フィルター",
        "filter.title": "フィルター",
        "filter.category": "カテゴリー",
        "filter.availability": "在庫状況",
        "filter.instock": "在庫あり",
        "filter.outstock": "在庫なし",
        "filter.price": "価格",
        "sort.by": "並び替え:",
        "sort.featured": "おすすめ",
        "sort.bestselling": "ベストセラー",
        "sort.az": "アルファベット順, A-Z",
        "sort.za": "アルファベット順, Z-A",
        "sort.lowhigh": "価格が安い順",
        "sort.highlow": "価格が高い順",
        "sort.oldnew": "日付が古い順",
        "sort.newold": "日付が新しい順",
        "footer.information": "情報",
        "footer.collection": "コレクション",
        "footer.about": "私たちについて",
        "footer.contactus": "連絡先",
        "product.ombre2025": "オンブル 2025",
        "product.urbane1": "アーバンデジタルローンプリント",
        "product.urbane2": "アーバンデジタルローン VOL II",
        "addtocart": "カートに追加",
        "buynow": "今すぐ購入",
        "pagination.prev": "&larr;",
        "pagination.next": "&rarr;",
        "contact.title": "お問い合わせ",
        "sidebar.close": "×",
        "contact.dropaline": "ご連絡ください",
        "contact.or": "または",
        "contact.messageinsta": "Instagramでメッセージを送る",
        "contact.name": "お名前",
        "contact.email": "メールアドレス",
        "contact.number": "電話番号",
        "contact.story": "ご要望をお聞かせください",
        "contact.submit": "送信",
        "contact.offer": "私たちの提供内容",
        "contact.qualitytitle": "品質保証",
        "contact.quality": "当社の生地は厳格な品質管理と徹底したテストを受けているため、お客様は安心してご利用いただけます。",
        "contact.bespoketitle": "オーダーメイド対応",
        "contact.bespoke": "豊富な生地ライブラリからお選びいただくか、オリジナルの生地を一緒に作成することも可能です。",
        "contact.servicetitle": "比類なきカスタマーサービス",
        "contact.service": "お客様のために私たちのチームが全力でサポートします。カスタマーサービスは常に最優先事項です。",
        "footer.menu": "メニュー",
        "footer.privacy": "プライバシーポリシー",
        "footer.cookie": "クッキーポリシー",
        "footer.designby": "ウェブサイトデザイン：",
        "footer.nasir": "@nasir"
    }
};
